---
name: CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CI: true
    strategy:
      matrix:
        node-version: [14.x, 16.x]
    name: Use Node.js ${{ matrix.node-version }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: yarn install
        run: yarn
      - name: Linting
        if: ${{ matrix.node-version == '16.x' }}
        run: yarn lint
      - name: Unittesting
        run: yarn test
      - name: Coverage
        if: ${{ matrix.node-version == '16.x' }}
        run: yarn coverage && yarn codecov -t ${{ secrets.CODECOV_TOKEN }}
