---
name: Release Patch Version
on:
  workflow_dispatch:

jobs:
  publish:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
          registry-url: https://registry.npmjs.org/
      - name: Install dependencies
        run: yarn
      - name: Run lint
        run: yarn lint
      - name: Run tests
        run: yarn test
      - name: Create new Version
        run: |
            git config --global user.name 'CI'
            git config --global user.email 'nuxt-neo-ci@users.noreply.github.com'
            yarn release:patch
            git push --follow-tags
      - name: Publish to NPM
        run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Deploys Github Pages Docs
        run: yarn deploy:docs
